/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateRuleTuningExpressionRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRuleTuningExpressionRequestBody{}

// UpdateRuleTuningExpressionRequestBody struct for UpdateRuleTuningExpressionRequestBody
type UpdateRuleTuningExpressionRequestBody struct {
	Fields CreateRuleTuningExpressionRequestBodyFields `json:"fields"`
}

type _UpdateRuleTuningExpressionRequestBody UpdateRuleTuningExpressionRequestBody

// NewUpdateRuleTuningExpressionRequestBody instantiates a new UpdateRuleTuningExpressionRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRuleTuningExpressionRequestBody(fields CreateRuleTuningExpressionRequestBodyFields) *UpdateRuleTuningExpressionRequestBody {
	this := UpdateRuleTuningExpressionRequestBody{}
	this.Fields = fields
	return &this
}

// NewUpdateRuleTuningExpressionRequestBodyWithDefaults instantiates a new UpdateRuleTuningExpressionRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRuleTuningExpressionRequestBodyWithDefaults() *UpdateRuleTuningExpressionRequestBody {
	this := UpdateRuleTuningExpressionRequestBody{}
	return &this
}

// GetFields returns the Fields field value
func (o *UpdateRuleTuningExpressionRequestBody) GetFields() CreateRuleTuningExpressionRequestBodyFields {
	if o == nil {
		var ret CreateRuleTuningExpressionRequestBodyFields
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *UpdateRuleTuningExpressionRequestBody) GetFieldsOk() (*CreateRuleTuningExpressionRequestBodyFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fields, true
}

// SetFields sets field value
func (o *UpdateRuleTuningExpressionRequestBody) SetFields(v CreateRuleTuningExpressionRequestBodyFields) {
	o.Fields = v
}

func (o UpdateRuleTuningExpressionRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRuleTuningExpressionRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

func (o *UpdateRuleTuningExpressionRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRuleTuningExpressionRequestBody := _UpdateRuleTuningExpressionRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateRuleTuningExpressionRequestBody)

	if err != nil {
		return err
	}

	*o = UpdateRuleTuningExpressionRequestBody(varUpdateRuleTuningExpressionRequestBody)

	return err
}

type NullableUpdateRuleTuningExpressionRequestBody struct {
	value *UpdateRuleTuningExpressionRequestBody
	isSet bool
}

func (v NullableUpdateRuleTuningExpressionRequestBody) Get() *UpdateRuleTuningExpressionRequestBody {
	return v.value
}

func (v *NullableUpdateRuleTuningExpressionRequestBody) Set(val *UpdateRuleTuningExpressionRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRuleTuningExpressionRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRuleTuningExpressionRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRuleTuningExpressionRequestBody(val *UpdateRuleTuningExpressionRequestBody) *NullableUpdateRuleTuningExpressionRequestBody {
	return &NullableUpdateRuleTuningExpressionRequestBody{value: val, isSet: true}
}

func (v NullableUpdateRuleTuningExpressionRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRuleTuningExpressionRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


