/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateInsightFromSignalsRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInsightFromSignalsRequestBody{}

// CreateInsightFromSignalsRequestBody struct for CreateInsightFromSignalsRequestBody
type CreateInsightFromSignalsRequestBody struct {
	SignalIds []string `json:"signalIds"`
}

type _CreateInsightFromSignalsRequestBody CreateInsightFromSignalsRequestBody

// NewCreateInsightFromSignalsRequestBody instantiates a new CreateInsightFromSignalsRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInsightFromSignalsRequestBody(signalIds []string) *CreateInsightFromSignalsRequestBody {
	this := CreateInsightFromSignalsRequestBody{}
	this.SignalIds = signalIds
	return &this
}

// NewCreateInsightFromSignalsRequestBodyWithDefaults instantiates a new CreateInsightFromSignalsRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInsightFromSignalsRequestBodyWithDefaults() *CreateInsightFromSignalsRequestBody {
	this := CreateInsightFromSignalsRequestBody{}
	return &this
}

// GetSignalIds returns the SignalIds field value
func (o *CreateInsightFromSignalsRequestBody) GetSignalIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SignalIds
}

// GetSignalIdsOk returns a tuple with the SignalIds field value
// and a boolean to check if the value has been set.
func (o *CreateInsightFromSignalsRequestBody) GetSignalIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignalIds, true
}

// SetSignalIds sets field value
func (o *CreateInsightFromSignalsRequestBody) SetSignalIds(v []string) {
	o.SignalIds = v
}

func (o CreateInsightFromSignalsRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInsightFromSignalsRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signalIds"] = o.SignalIds
	return toSerialize, nil
}

func (o *CreateInsightFromSignalsRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signalIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInsightFromSignalsRequestBody := _CreateInsightFromSignalsRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateInsightFromSignalsRequestBody)

	if err != nil {
		return err
	}

	*o = CreateInsightFromSignalsRequestBody(varCreateInsightFromSignalsRequestBody)

	return err
}

type NullableCreateInsightFromSignalsRequestBody struct {
	value *CreateInsightFromSignalsRequestBody
	isSet bool
}

func (v NullableCreateInsightFromSignalsRequestBody) Get() *CreateInsightFromSignalsRequestBody {
	return v.value
}

func (v *NullableCreateInsightFromSignalsRequestBody) Set(val *CreateInsightFromSignalsRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInsightFromSignalsRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInsightFromSignalsRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInsightFromSignalsRequestBody(val *CreateInsightFromSignalsRequestBody) *NullableCreateInsightFromSignalsRequestBody {
	return &NullableCreateInsightFromSignalsRequestBody{value: val, isSet: true}
}

func (v NullableCreateInsightFromSignalsRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInsightFromSignalsRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


