/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAllEntitiesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllEntitiesResponse{}

// GetAllEntitiesResponse struct for GetAllEntitiesResponse
type GetAllEntitiesResponse struct {
	Data GetAllEntitiesResponseData `json:"data"`
}

type _GetAllEntitiesResponse GetAllEntitiesResponse

// NewGetAllEntitiesResponse instantiates a new GetAllEntitiesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllEntitiesResponse(data GetAllEntitiesResponseData) *GetAllEntitiesResponse {
	this := GetAllEntitiesResponse{}
	this.Data = data
	return &this
}

// NewGetAllEntitiesResponseWithDefaults instantiates a new GetAllEntitiesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllEntitiesResponseWithDefaults() *GetAllEntitiesResponse {
	this := GetAllEntitiesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetAllEntitiesResponse) GetData() GetAllEntitiesResponseData {
	if o == nil {
		var ret GetAllEntitiesResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAllEntitiesResponse) GetDataOk() (*GetAllEntitiesResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetAllEntitiesResponse) SetData(v GetAllEntitiesResponseData) {
	o.Data = v
}

func (o GetAllEntitiesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllEntitiesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetAllEntitiesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAllEntitiesResponse := _GetAllEntitiesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAllEntitiesResponse)

	if err != nil {
		return err
	}

	*o = GetAllEntitiesResponse(varGetAllEntitiesResponse)

	return err
}

type NullableGetAllEntitiesResponse struct {
	value *GetAllEntitiesResponse
	isSet bool
}

func (v NullableGetAllEntitiesResponse) Get() *GetAllEntitiesResponse {
	return v.value
}

func (v *NullableGetAllEntitiesResponse) Set(val *GetAllEntitiesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllEntitiesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllEntitiesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllEntitiesResponse(val *GetAllEntitiesResponse) *NullableGetAllEntitiesResponse {
	return &NullableGetAllEntitiesResponse{value: val, isSet: true}
}

func (v NullableGetAllEntitiesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllEntitiesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


