/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateInventoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateInventoryResponse{}

// UpdateInventoryResponse struct for UpdateInventoryResponse
type UpdateInventoryResponse struct {
	Data Inventory `json:"data"`
}

type _UpdateInventoryResponse UpdateInventoryResponse

// NewUpdateInventoryResponse instantiates a new UpdateInventoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateInventoryResponse(data Inventory) *UpdateInventoryResponse {
	this := UpdateInventoryResponse{}
	this.Data = data
	return &this
}

// NewUpdateInventoryResponseWithDefaults instantiates a new UpdateInventoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateInventoryResponseWithDefaults() *UpdateInventoryResponse {
	this := UpdateInventoryResponse{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateInventoryResponse) GetData() Inventory {
	if o == nil {
		var ret Inventory
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateInventoryResponse) GetDataOk() (*Inventory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateInventoryResponse) SetData(v Inventory) {
	o.Data = v
}

func (o UpdateInventoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateInventoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateInventoryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateInventoryResponse := _UpdateInventoryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateInventoryResponse)

	if err != nil {
		return err
	}

	*o = UpdateInventoryResponse(varUpdateInventoryResponse)

	return err
}

type NullableUpdateInventoryResponse struct {
	value *UpdateInventoryResponse
	isSet bool
}

func (v NullableUpdateInventoryResponse) Get() *UpdateInventoryResponse {
	return v.value
}

func (v *NullableUpdateInventoryResponse) Set(val *UpdateInventoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInventoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInventoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInventoryResponse(val *UpdateInventoryResponse) *NullableUpdateInventoryResponse {
	return &NullableUpdateInventoryResponse{value: val, isSet: true}
}

func (v NullableUpdateInventoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInventoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


