/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetThreatIntelSourceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetThreatIntelSourceResponse{}

// GetThreatIntelSourceResponse struct for GetThreatIntelSourceResponse
type GetThreatIntelSourceResponse struct {
	Data ThreatIntelSource `json:"data"`
}

type _GetThreatIntelSourceResponse GetThreatIntelSourceResponse

// NewGetThreatIntelSourceResponse instantiates a new GetThreatIntelSourceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetThreatIntelSourceResponse(data ThreatIntelSource) *GetThreatIntelSourceResponse {
	this := GetThreatIntelSourceResponse{}
	this.Data = data
	return &this
}

// NewGetThreatIntelSourceResponseWithDefaults instantiates a new GetThreatIntelSourceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetThreatIntelSourceResponseWithDefaults() *GetThreatIntelSourceResponse {
	this := GetThreatIntelSourceResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetThreatIntelSourceResponse) GetData() ThreatIntelSource {
	if o == nil {
		var ret ThreatIntelSource
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetThreatIntelSourceResponse) GetDataOk() (*ThreatIntelSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetThreatIntelSourceResponse) SetData(v ThreatIntelSource) {
	o.Data = v
}

func (o GetThreatIntelSourceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetThreatIntelSourceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetThreatIntelSourceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetThreatIntelSourceResponse := _GetThreatIntelSourceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetThreatIntelSourceResponse)

	if err != nil {
		return err
	}

	*o = GetThreatIntelSourceResponse(varGetThreatIntelSourceResponse)

	return err
}

type NullableGetThreatIntelSourceResponse struct {
	value *GetThreatIntelSourceResponse
	isSet bool
}

func (v NullableGetThreatIntelSourceResponse) Get() *GetThreatIntelSourceResponse {
	return v.value
}

func (v *NullableGetThreatIntelSourceResponse) Set(val *GetThreatIntelSourceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetThreatIntelSourceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetThreatIntelSourceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetThreatIntelSourceResponse(val *GetThreatIntelSourceResponse) *NullableGetThreatIntelSourceResponse {
	return &NullableGetThreatIntelSourceResponse{value: val, isSet: true}
}

func (v NullableGetThreatIntelSourceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetThreatIntelSourceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


