/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRuleTuningExpressionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRuleTuningExpressionResponse{}

// GetRuleTuningExpressionResponse struct for GetRuleTuningExpressionResponse
type GetRuleTuningExpressionResponse struct {
	Data RuleTuningExpression `json:"data"`
}

type _GetRuleTuningExpressionResponse GetRuleTuningExpressionResponse

// NewGetRuleTuningExpressionResponse instantiates a new GetRuleTuningExpressionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRuleTuningExpressionResponse(data RuleTuningExpression) *GetRuleTuningExpressionResponse {
	this := GetRuleTuningExpressionResponse{}
	this.Data = data
	return &this
}

// NewGetRuleTuningExpressionResponseWithDefaults instantiates a new GetRuleTuningExpressionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRuleTuningExpressionResponseWithDefaults() *GetRuleTuningExpressionResponse {
	this := GetRuleTuningExpressionResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetRuleTuningExpressionResponse) GetData() RuleTuningExpression {
	if o == nil {
		var ret RuleTuningExpression
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetRuleTuningExpressionResponse) GetDataOk() (*RuleTuningExpression, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetRuleTuningExpressionResponse) SetData(v RuleTuningExpression) {
	o.Data = v
}

func (o GetRuleTuningExpressionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRuleTuningExpressionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetRuleTuningExpressionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRuleTuningExpressionResponse := _GetRuleTuningExpressionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRuleTuningExpressionResponse)

	if err != nil {
		return err
	}

	*o = GetRuleTuningExpressionResponse(varGetRuleTuningExpressionResponse)

	return err
}

type NullableGetRuleTuningExpressionResponse struct {
	value *GetRuleTuningExpressionResponse
	isSet bool
}

func (v NullableGetRuleTuningExpressionResponse) Get() *GetRuleTuningExpressionResponse {
	return v.value
}

func (v *NullableGetRuleTuningExpressionResponse) Set(val *GetRuleTuningExpressionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRuleTuningExpressionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRuleTuningExpressionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRuleTuningExpressionResponse(val *GetRuleTuningExpressionResponse) *NullableGetRuleTuningExpressionResponse {
	return &NullableGetRuleTuningExpressionResponse{value: val, isSet: true}
}

func (v NullableGetRuleTuningExpressionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRuleTuningExpressionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


