/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetSuppressListsResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSuppressListsResponseData{}

// GetSuppressListsResponseData struct for GetSuppressListsResponseData
type GetSuppressListsResponseData struct {
	HasNextPage bool `json:"hasNextPage"`
	Total int32 `json:"total"`
	Objects []SuppressList `json:"objects"`
}

type _GetSuppressListsResponseData GetSuppressListsResponseData

// NewGetSuppressListsResponseData instantiates a new GetSuppressListsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSuppressListsResponseData(hasNextPage bool, total int32, objects []SuppressList) *GetSuppressListsResponseData {
	this := GetSuppressListsResponseData{}
	this.HasNextPage = hasNextPage
	this.Total = total
	this.Objects = objects
	return &this
}

// NewGetSuppressListsResponseDataWithDefaults instantiates a new GetSuppressListsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSuppressListsResponseDataWithDefaults() *GetSuppressListsResponseData {
	this := GetSuppressListsResponseData{}
	return &this
}

// GetHasNextPage returns the HasNextPage field value
func (o *GetSuppressListsResponseData) GetHasNextPage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNextPage
}

// GetHasNextPageOk returns a tuple with the HasNextPage field value
// and a boolean to check if the value has been set.
func (o *GetSuppressListsResponseData) GetHasNextPageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasNextPage, true
}

// SetHasNextPage sets field value
func (o *GetSuppressListsResponseData) SetHasNextPage(v bool) {
	o.HasNextPage = v
}

// GetTotal returns the Total field value
func (o *GetSuppressListsResponseData) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetSuppressListsResponseData) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetSuppressListsResponseData) SetTotal(v int32) {
	o.Total = v
}

// GetObjects returns the Objects field value
func (o *GetSuppressListsResponseData) GetObjects() []SuppressList {
	if o == nil {
		var ret []SuppressList
		return ret
	}

	return o.Objects
}

// GetObjectsOk returns a tuple with the Objects field value
// and a boolean to check if the value has been set.
func (o *GetSuppressListsResponseData) GetObjectsOk() ([]SuppressList, bool) {
	if o == nil {
		return nil, false
	}
	return o.Objects, true
}

// SetObjects sets field value
func (o *GetSuppressListsResponseData) SetObjects(v []SuppressList) {
	o.Objects = v
}

func (o GetSuppressListsResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSuppressListsResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hasNextPage"] = o.HasNextPage
	toSerialize["total"] = o.Total
	toSerialize["objects"] = o.Objects
	return toSerialize, nil
}

func (o *GetSuppressListsResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hasNextPage",
		"total",
		"objects",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSuppressListsResponseData := _GetSuppressListsResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSuppressListsResponseData)

	if err != nil {
		return err
	}

	*o = GetSuppressListsResponseData(varGetSuppressListsResponseData)

	return err
}

type NullableGetSuppressListsResponseData struct {
	value *GetSuppressListsResponseData
	isSet bool
}

func (v NullableGetSuppressListsResponseData) Get() *GetSuppressListsResponseData {
	return v.value
}

func (v *NullableGetSuppressListsResponseData) Set(val *GetSuppressListsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSuppressListsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSuppressListsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSuppressListsResponseData(val *GetSuppressListsResponseData) *NullableGetSuppressListsResponseData {
	return &NullableGetSuppressListsResponseData{value: val, isSet: true}
}

func (v NullableGetSuppressListsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSuppressListsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


