/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetCustomerSourcedLookupTableResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCustomerSourcedLookupTableResponse{}

// GetCustomerSourcedLookupTableResponse struct for GetCustomerSourcedLookupTableResponse
type GetCustomerSourcedLookupTableResponse struct {
	Data GetCustomerSourcedLookupTableResponseData `json:"data"`
}

type _GetCustomerSourcedLookupTableResponse GetCustomerSourcedLookupTableResponse

// NewGetCustomerSourcedLookupTableResponse instantiates a new GetCustomerSourcedLookupTableResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCustomerSourcedLookupTableResponse(data GetCustomerSourcedLookupTableResponseData) *GetCustomerSourcedLookupTableResponse {
	this := GetCustomerSourcedLookupTableResponse{}
	this.Data = data
	return &this
}

// NewGetCustomerSourcedLookupTableResponseWithDefaults instantiates a new GetCustomerSourcedLookupTableResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustomerSourcedLookupTableResponseWithDefaults() *GetCustomerSourcedLookupTableResponse {
	this := GetCustomerSourcedLookupTableResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetCustomerSourcedLookupTableResponse) GetData() GetCustomerSourcedLookupTableResponseData {
	if o == nil {
		var ret GetCustomerSourcedLookupTableResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetCustomerSourcedLookupTableResponse) GetDataOk() (*GetCustomerSourcedLookupTableResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetCustomerSourcedLookupTableResponse) SetData(v GetCustomerSourcedLookupTableResponseData) {
	o.Data = v
}

func (o GetCustomerSourcedLookupTableResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCustomerSourcedLookupTableResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetCustomerSourcedLookupTableResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCustomerSourcedLookupTableResponse := _GetCustomerSourcedLookupTableResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCustomerSourcedLookupTableResponse)

	if err != nil {
		return err
	}

	*o = GetCustomerSourcedLookupTableResponse(varGetCustomerSourcedLookupTableResponse)

	return err
}

type NullableGetCustomerSourcedLookupTableResponse struct {
	value *GetCustomerSourcedLookupTableResponse
	isSet bool
}

func (v NullableGetCustomerSourcedLookupTableResponse) Get() *GetCustomerSourcedLookupTableResponse {
	return v.value
}

func (v *NullableGetCustomerSourcedLookupTableResponse) Set(val *GetCustomerSourcedLookupTableResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustomerSourcedLookupTableResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustomerSourcedLookupTableResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCustomerSourcedLookupTableResponse(val *GetCustomerSourcedLookupTableResponse) *NullableGetCustomerSourcedLookupTableResponse {
	return &NullableGetCustomerSourcedLookupTableResponse{value: val, isSet: true}
}

func (v NullableGetCustomerSourcedLookupTableResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustomerSourcedLookupTableResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


