/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteEntityNoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteEntityNoteResponse{}

// DeleteEntityNoteResponse struct for DeleteEntityNoteResponse
type DeleteEntityNoteResponse struct {
	Data DeleteContextActionResponseData `json:"data"`
}

type _DeleteEntityNoteResponse DeleteEntityNoteResponse

// NewDeleteEntityNoteResponse instantiates a new DeleteEntityNoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteEntityNoteResponse(data DeleteContextActionResponseData) *DeleteEntityNoteResponse {
	this := DeleteEntityNoteResponse{}
	this.Data = data
	return &this
}

// NewDeleteEntityNoteResponseWithDefaults instantiates a new DeleteEntityNoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteEntityNoteResponseWithDefaults() *DeleteEntityNoteResponse {
	this := DeleteEntityNoteResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteEntityNoteResponse) GetData() DeleteContextActionResponseData {
	if o == nil {
		var ret DeleteContextActionResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteEntityNoteResponse) GetDataOk() (*DeleteContextActionResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteEntityNoteResponse) SetData(v DeleteContextActionResponseData) {
	o.Data = v
}

func (o DeleteEntityNoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteEntityNoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteEntityNoteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteEntityNoteResponse := _DeleteEntityNoteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteEntityNoteResponse)

	if err != nil {
		return err
	}

	*o = DeleteEntityNoteResponse(varDeleteEntityNoteResponse)

	return err
}

type NullableDeleteEntityNoteResponse struct {
	value *DeleteEntityNoteResponse
	isSet bool
}

func (v NullableDeleteEntityNoteResponse) Get() *DeleteEntityNoteResponse {
	return v.value
}

func (v *NullableDeleteEntityNoteResponse) Set(val *DeleteEntityNoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteEntityNoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteEntityNoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteEntityNoteResponse(val *DeleteEntityNoteResponse) *NullableDeleteEntityNoteResponse {
	return &NullableDeleteEntityNoteResponse{value: val, isSet: true}
}

func (v NullableDeleteEntityNoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteEntityNoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


