/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateLogMappingRequestBodyFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLogMappingRequestBodyFields{}

// CreateLogMappingRequestBodyFields struct for CreateLogMappingRequestBodyFields
type CreateLogMappingRequestBodyFields struct {
	Name string `json:"name"`
	ParentId *string `json:"parentId,omitempty"`
	Fields []CreateLogMappingRequestBodyFieldsFieldsInner `json:"fields"`
	SkippedValues []string `json:"skippedValues,omitempty"`
	UnstructuredFields *CreateLogMappingRequestBodyFieldsUnstructuredFields `json:"unstructuredFields,omitempty"`
	StructuredFields *CreateLogMappingRequestBodyFieldsStructuredFields `json:"structuredFields,omitempty"`
	StructuredInputs []CreateLogMappingRequestBodyFieldsStructuredFields `json:"structuredInputs,omitempty"`
	RecordType string `json:"recordType"`
	ProductGuid string `json:"productGuid"`
	RelatesEntities *bool `json:"relatesEntities,omitempty"`
	Enabled bool `json:"enabled"`
}

type _CreateLogMappingRequestBodyFields CreateLogMappingRequestBodyFields

// NewCreateLogMappingRequestBodyFields instantiates a new CreateLogMappingRequestBodyFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLogMappingRequestBodyFields(name string, fields []CreateLogMappingRequestBodyFieldsFieldsInner, recordType string, productGuid string, enabled bool) *CreateLogMappingRequestBodyFields {
	this := CreateLogMappingRequestBodyFields{}
	this.Name = name
	this.Fields = fields
	this.RecordType = recordType
	this.ProductGuid = productGuid
	this.Enabled = enabled
	return &this
}

// NewCreateLogMappingRequestBodyFieldsWithDefaults instantiates a new CreateLogMappingRequestBodyFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLogMappingRequestBodyFieldsWithDefaults() *CreateLogMappingRequestBodyFields {
	this := CreateLogMappingRequestBodyFields{}
	return &this
}

// GetName returns the Name field value
func (o *CreateLogMappingRequestBodyFields) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateLogMappingRequestBodyFields) SetName(v string) {
	o.Name = v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *CreateLogMappingRequestBodyFields) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *CreateLogMappingRequestBodyFields) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *CreateLogMappingRequestBodyFields) SetParentId(v string) {
	o.ParentId = &v
}

// GetFields returns the Fields field value
func (o *CreateLogMappingRequestBodyFields) GetFields() []CreateLogMappingRequestBodyFieldsFieldsInner {
	if o == nil {
		var ret []CreateLogMappingRequestBodyFieldsFieldsInner
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetFieldsOk() ([]CreateLogMappingRequestBodyFieldsFieldsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *CreateLogMappingRequestBodyFields) SetFields(v []CreateLogMappingRequestBodyFieldsFieldsInner) {
	o.Fields = v
}

// GetSkippedValues returns the SkippedValues field value if set, zero value otherwise.
func (o *CreateLogMappingRequestBodyFields) GetSkippedValues() []string {
	if o == nil || IsNil(o.SkippedValues) {
		var ret []string
		return ret
	}
	return o.SkippedValues
}

// GetSkippedValuesOk returns a tuple with the SkippedValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetSkippedValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.SkippedValues) {
		return nil, false
	}
	return o.SkippedValues, true
}

// HasSkippedValues returns a boolean if a field has been set.
func (o *CreateLogMappingRequestBodyFields) HasSkippedValues() bool {
	if o != nil && !IsNil(o.SkippedValues) {
		return true
	}

	return false
}

// SetSkippedValues gets a reference to the given []string and assigns it to the SkippedValues field.
func (o *CreateLogMappingRequestBodyFields) SetSkippedValues(v []string) {
	o.SkippedValues = v
}

// GetUnstructuredFields returns the UnstructuredFields field value if set, zero value otherwise.
func (o *CreateLogMappingRequestBodyFields) GetUnstructuredFields() CreateLogMappingRequestBodyFieldsUnstructuredFields {
	if o == nil || IsNil(o.UnstructuredFields) {
		var ret CreateLogMappingRequestBodyFieldsUnstructuredFields
		return ret
	}
	return *o.UnstructuredFields
}

// GetUnstructuredFieldsOk returns a tuple with the UnstructuredFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetUnstructuredFieldsOk() (*CreateLogMappingRequestBodyFieldsUnstructuredFields, bool) {
	if o == nil || IsNil(o.UnstructuredFields) {
		return nil, false
	}
	return o.UnstructuredFields, true
}

// HasUnstructuredFields returns a boolean if a field has been set.
func (o *CreateLogMappingRequestBodyFields) HasUnstructuredFields() bool {
	if o != nil && !IsNil(o.UnstructuredFields) {
		return true
	}

	return false
}

// SetUnstructuredFields gets a reference to the given CreateLogMappingRequestBodyFieldsUnstructuredFields and assigns it to the UnstructuredFields field.
func (o *CreateLogMappingRequestBodyFields) SetUnstructuredFields(v CreateLogMappingRequestBodyFieldsUnstructuredFields) {
	o.UnstructuredFields = &v
}

// GetStructuredFields returns the StructuredFields field value if set, zero value otherwise.
func (o *CreateLogMappingRequestBodyFields) GetStructuredFields() CreateLogMappingRequestBodyFieldsStructuredFields {
	if o == nil || IsNil(o.StructuredFields) {
		var ret CreateLogMappingRequestBodyFieldsStructuredFields
		return ret
	}
	return *o.StructuredFields
}

// GetStructuredFieldsOk returns a tuple with the StructuredFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetStructuredFieldsOk() (*CreateLogMappingRequestBodyFieldsStructuredFields, bool) {
	if o == nil || IsNil(o.StructuredFields) {
		return nil, false
	}
	return o.StructuredFields, true
}

// HasStructuredFields returns a boolean if a field has been set.
func (o *CreateLogMappingRequestBodyFields) HasStructuredFields() bool {
	if o != nil && !IsNil(o.StructuredFields) {
		return true
	}

	return false
}

// SetStructuredFields gets a reference to the given CreateLogMappingRequestBodyFieldsStructuredFields and assigns it to the StructuredFields field.
func (o *CreateLogMappingRequestBodyFields) SetStructuredFields(v CreateLogMappingRequestBodyFieldsStructuredFields) {
	o.StructuredFields = &v
}

// GetStructuredInputs returns the StructuredInputs field value if set, zero value otherwise.
func (o *CreateLogMappingRequestBodyFields) GetStructuredInputs() []CreateLogMappingRequestBodyFieldsStructuredFields {
	if o == nil || IsNil(o.StructuredInputs) {
		var ret []CreateLogMappingRequestBodyFieldsStructuredFields
		return ret
	}
	return o.StructuredInputs
}

// GetStructuredInputsOk returns a tuple with the StructuredInputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetStructuredInputsOk() ([]CreateLogMappingRequestBodyFieldsStructuredFields, bool) {
	if o == nil || IsNil(o.StructuredInputs) {
		return nil, false
	}
	return o.StructuredInputs, true
}

// HasStructuredInputs returns a boolean if a field has been set.
func (o *CreateLogMappingRequestBodyFields) HasStructuredInputs() bool {
	if o != nil && !IsNil(o.StructuredInputs) {
		return true
	}

	return false
}

// SetStructuredInputs gets a reference to the given []CreateLogMappingRequestBodyFieldsStructuredFields and assigns it to the StructuredInputs field.
func (o *CreateLogMappingRequestBodyFields) SetStructuredInputs(v []CreateLogMappingRequestBodyFieldsStructuredFields) {
	o.StructuredInputs = v
}

// GetRecordType returns the RecordType field value
func (o *CreateLogMappingRequestBodyFields) GetRecordType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecordType
}

// GetRecordTypeOk returns a tuple with the RecordType field value
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetRecordTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordType, true
}

// SetRecordType sets field value
func (o *CreateLogMappingRequestBodyFields) SetRecordType(v string) {
	o.RecordType = v
}

// GetProductGuid returns the ProductGuid field value
func (o *CreateLogMappingRequestBodyFields) GetProductGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductGuid
}

// GetProductGuidOk returns a tuple with the ProductGuid field value
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetProductGuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductGuid, true
}

// SetProductGuid sets field value
func (o *CreateLogMappingRequestBodyFields) SetProductGuid(v string) {
	o.ProductGuid = v
}

// GetRelatesEntities returns the RelatesEntities field value if set, zero value otherwise.
func (o *CreateLogMappingRequestBodyFields) GetRelatesEntities() bool {
	if o == nil || IsNil(o.RelatesEntities) {
		var ret bool
		return ret
	}
	return *o.RelatesEntities
}

// GetRelatesEntitiesOk returns a tuple with the RelatesEntities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetRelatesEntitiesOk() (*bool, bool) {
	if o == nil || IsNil(o.RelatesEntities) {
		return nil, false
	}
	return o.RelatesEntities, true
}

// HasRelatesEntities returns a boolean if a field has been set.
func (o *CreateLogMappingRequestBodyFields) HasRelatesEntities() bool {
	if o != nil && !IsNil(o.RelatesEntities) {
		return true
	}

	return false
}

// SetRelatesEntities gets a reference to the given bool and assigns it to the RelatesEntities field.
func (o *CreateLogMappingRequestBodyFields) SetRelatesEntities(v bool) {
	o.RelatesEntities = &v
}

// GetEnabled returns the Enabled field value
func (o *CreateLogMappingRequestBodyFields) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFields) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CreateLogMappingRequestBodyFields) SetEnabled(v bool) {
	o.Enabled = v
}

func (o CreateLogMappingRequestBodyFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLogMappingRequestBodyFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	toSerialize["fields"] = o.Fields
	if !IsNil(o.SkippedValues) {
		toSerialize["skippedValues"] = o.SkippedValues
	}
	if !IsNil(o.UnstructuredFields) {
		toSerialize["unstructuredFields"] = o.UnstructuredFields
	}
	if !IsNil(o.StructuredFields) {
		toSerialize["structuredFields"] = o.StructuredFields
	}
	if !IsNil(o.StructuredInputs) {
		toSerialize["structuredInputs"] = o.StructuredInputs
	}
	toSerialize["recordType"] = o.RecordType
	toSerialize["productGuid"] = o.ProductGuid
	if !IsNil(o.RelatesEntities) {
		toSerialize["relatesEntities"] = o.RelatesEntities
	}
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *CreateLogMappingRequestBodyFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"fields",
		"recordType",
		"productGuid",
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLogMappingRequestBodyFields := _CreateLogMappingRequestBodyFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateLogMappingRequestBodyFields)

	if err != nil {
		return err
	}

	*o = CreateLogMappingRequestBodyFields(varCreateLogMappingRequestBodyFields)

	return err
}

type NullableCreateLogMappingRequestBodyFields struct {
	value *CreateLogMappingRequestBodyFields
	isSet bool
}

func (v NullableCreateLogMappingRequestBodyFields) Get() *CreateLogMappingRequestBodyFields {
	return v.value
}

func (v *NullableCreateLogMappingRequestBodyFields) Set(val *CreateLogMappingRequestBodyFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLogMappingRequestBodyFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLogMappingRequestBodyFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLogMappingRequestBodyFields(val *CreateLogMappingRequestBodyFields) *NullableCreateLogMappingRequestBodyFields {
	return &NullableCreateLogMappingRequestBodyFields{value: val, isSet: true}
}

func (v NullableCreateLogMappingRequestBodyFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLogMappingRequestBodyFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


