/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteEntityGroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteEntityGroupResponse{}

// DeleteEntityGroupResponse struct for DeleteEntityGroupResponse
type DeleteEntityGroupResponse struct {
	Data DeleteContextActionResponseData `json:"data"`
}

type _DeleteEntityGroupResponse DeleteEntityGroupResponse

// NewDeleteEntityGroupResponse instantiates a new DeleteEntityGroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteEntityGroupResponse(data DeleteContextActionResponseData) *DeleteEntityGroupResponse {
	this := DeleteEntityGroupResponse{}
	this.Data = data
	return &this
}

// NewDeleteEntityGroupResponseWithDefaults instantiates a new DeleteEntityGroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteEntityGroupResponseWithDefaults() *DeleteEntityGroupResponse {
	this := DeleteEntityGroupResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteEntityGroupResponse) GetData() DeleteContextActionResponseData {
	if o == nil {
		var ret DeleteContextActionResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteEntityGroupResponse) GetDataOk() (*DeleteContextActionResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteEntityGroupResponse) SetData(v DeleteContextActionResponseData) {
	o.Data = v
}

func (o DeleteEntityGroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteEntityGroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteEntityGroupResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteEntityGroupResponse := _DeleteEntityGroupResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteEntityGroupResponse)

	if err != nil {
		return err
	}

	*o = DeleteEntityGroupResponse(varDeleteEntityGroupResponse)

	return err
}

type NullableDeleteEntityGroupResponse struct {
	value *DeleteEntityGroupResponse
	isSet bool
}

func (v NullableDeleteEntityGroupResponse) Get() *DeleteEntityGroupResponse {
	return v.value
}

func (v *NullableDeleteEntityGroupResponse) Set(val *DeleteEntityGroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteEntityGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteEntityGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteEntityGroupResponse(val *DeleteEntityGroupResponse) *NullableDeleteEntityGroupResponse {
	return &NullableDeleteEntityGroupResponse{value: val, isSet: true}
}

func (v NullableDeleteEntityGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteEntityGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


