/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAllSignalsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllSignalsResponse{}

// GetAllSignalsResponse struct for GetAllSignalsResponse
type GetAllSignalsResponse struct {
	Data GetAllSignalsResponseData `json:"data"`
}

type _GetAllSignalsResponse GetAllSignalsResponse

// NewGetAllSignalsResponse instantiates a new GetAllSignalsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllSignalsResponse(data GetAllSignalsResponseData) *GetAllSignalsResponse {
	this := GetAllSignalsResponse{}
	this.Data = data
	return &this
}

// NewGetAllSignalsResponseWithDefaults instantiates a new GetAllSignalsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllSignalsResponseWithDefaults() *GetAllSignalsResponse {
	this := GetAllSignalsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetAllSignalsResponse) GetData() GetAllSignalsResponseData {
	if o == nil {
		var ret GetAllSignalsResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAllSignalsResponse) GetDataOk() (*GetAllSignalsResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetAllSignalsResponse) SetData(v GetAllSignalsResponseData) {
	o.Data = v
}

func (o GetAllSignalsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllSignalsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetAllSignalsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAllSignalsResponse := _GetAllSignalsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAllSignalsResponse)

	if err != nil {
		return err
	}

	*o = GetAllSignalsResponse(varGetAllSignalsResponse)

	return err
}

type NullableGetAllSignalsResponse struct {
	value *GetAllSignalsResponse
	isSet bool
}

func (v NullableGetAllSignalsResponse) Get() *GetAllSignalsResponse {
	return v.value
}

func (v *NullableGetAllSignalsResponse) Set(val *GetAllSignalsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllSignalsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllSignalsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllSignalsResponse(val *GetAllSignalsResponse) *NullableGetAllSignalsResponse {
	return &NullableGetAllSignalsResponse{value: val, isSet: true}
}

func (v NullableGetAllSignalsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllSignalsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


