/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRulesResponseDataObjectsInnerOneOfTagsOverride type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRulesResponseDataObjectsInnerOneOfTagsOverride{}

// GetRulesResponseDataObjectsInnerOneOfTagsOverride struct for GetRulesResponseDataObjectsInnerOneOfTagsOverride
type GetRulesResponseDataObjectsInnerOneOfTagsOverride struct {
	Original []string `json:"original,omitempty"`
	Override []string `json:"override,omitempty"`
}

// NewGetRulesResponseDataObjectsInnerOneOfTagsOverride instantiates a new GetRulesResponseDataObjectsInnerOneOfTagsOverride object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRulesResponseDataObjectsInnerOneOfTagsOverride() *GetRulesResponseDataObjectsInnerOneOfTagsOverride {
	this := GetRulesResponseDataObjectsInnerOneOfTagsOverride{}
	return &this
}

// NewGetRulesResponseDataObjectsInnerOneOfTagsOverrideWithDefaults instantiates a new GetRulesResponseDataObjectsInnerOneOfTagsOverride object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRulesResponseDataObjectsInnerOneOfTagsOverrideWithDefaults() *GetRulesResponseDataObjectsInnerOneOfTagsOverride {
	this := GetRulesResponseDataObjectsInnerOneOfTagsOverride{}
	return &this
}

// GetOriginal returns the Original field value if set, zero value otherwise.
func (o *GetRulesResponseDataObjectsInnerOneOfTagsOverride) GetOriginal() []string {
	if o == nil || IsNil(o.Original) {
		var ret []string
		return ret
	}
	return o.Original
}

// GetOriginalOk returns a tuple with the Original field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRulesResponseDataObjectsInnerOneOfTagsOverride) GetOriginalOk() ([]string, bool) {
	if o == nil || IsNil(o.Original) {
		return nil, false
	}
	return o.Original, true
}

// HasOriginal returns a boolean if a field has been set.
func (o *GetRulesResponseDataObjectsInnerOneOfTagsOverride) HasOriginal() bool {
	if o != nil && !IsNil(o.Original) {
		return true
	}

	return false
}

// SetOriginal gets a reference to the given []string and assigns it to the Original field.
func (o *GetRulesResponseDataObjectsInnerOneOfTagsOverride) SetOriginal(v []string) {
	o.Original = v
}

// GetOverride returns the Override field value if set, zero value otherwise.
func (o *GetRulesResponseDataObjectsInnerOneOfTagsOverride) GetOverride() []string {
	if o == nil || IsNil(o.Override) {
		var ret []string
		return ret
	}
	return o.Override
}

// GetOverrideOk returns a tuple with the Override field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRulesResponseDataObjectsInnerOneOfTagsOverride) GetOverrideOk() ([]string, bool) {
	if o == nil || IsNil(o.Override) {
		return nil, false
	}
	return o.Override, true
}

// HasOverride returns a boolean if a field has been set.
func (o *GetRulesResponseDataObjectsInnerOneOfTagsOverride) HasOverride() bool {
	if o != nil && !IsNil(o.Override) {
		return true
	}

	return false
}

// SetOverride gets a reference to the given []string and assigns it to the Override field.
func (o *GetRulesResponseDataObjectsInnerOneOfTagsOverride) SetOverride(v []string) {
	o.Override = v
}

func (o GetRulesResponseDataObjectsInnerOneOfTagsOverride) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRulesResponseDataObjectsInnerOneOfTagsOverride) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Original) {
		toSerialize["original"] = o.Original
	}
	if !IsNil(o.Override) {
		toSerialize["override"] = o.Override
	}
	return toSerialize, nil
}

type NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride struct {
	value *GetRulesResponseDataObjectsInnerOneOfTagsOverride
	isSet bool
}

func (v NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride) Get() *GetRulesResponseDataObjectsInnerOneOfTagsOverride {
	return v.value
}

func (v *NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride) Set(val *GetRulesResponseDataObjectsInnerOneOfTagsOverride) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRulesResponseDataObjectsInnerOneOfTagsOverride(val *GetRulesResponseDataObjectsInnerOneOfTagsOverride) *NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride {
	return &NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride{value: val, isSet: true}
}

func (v NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRulesResponseDataObjectsInnerOneOfTagsOverride) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


