/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateLogMappingRequestBodyFieldsUnstructuredFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLogMappingRequestBodyFieldsUnstructuredFields{}

// CreateLogMappingRequestBodyFieldsUnstructuredFields struct for CreateLogMappingRequestBodyFieldsUnstructuredFields
type CreateLogMappingRequestBodyFieldsUnstructuredFields struct {
	PatternNames []string `json:"patternNames"`
}

type _CreateLogMappingRequestBodyFieldsUnstructuredFields CreateLogMappingRequestBodyFieldsUnstructuredFields

// NewCreateLogMappingRequestBodyFieldsUnstructuredFields instantiates a new CreateLogMappingRequestBodyFieldsUnstructuredFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLogMappingRequestBodyFieldsUnstructuredFields(patternNames []string) *CreateLogMappingRequestBodyFieldsUnstructuredFields {
	this := CreateLogMappingRequestBodyFieldsUnstructuredFields{}
	this.PatternNames = patternNames
	return &this
}

// NewCreateLogMappingRequestBodyFieldsUnstructuredFieldsWithDefaults instantiates a new CreateLogMappingRequestBodyFieldsUnstructuredFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLogMappingRequestBodyFieldsUnstructuredFieldsWithDefaults() *CreateLogMappingRequestBodyFieldsUnstructuredFields {
	this := CreateLogMappingRequestBodyFieldsUnstructuredFields{}
	return &this
}

// GetPatternNames returns the PatternNames field value
func (o *CreateLogMappingRequestBodyFieldsUnstructuredFields) GetPatternNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PatternNames
}

// GetPatternNamesOk returns a tuple with the PatternNames field value
// and a boolean to check if the value has been set.
func (o *CreateLogMappingRequestBodyFieldsUnstructuredFields) GetPatternNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PatternNames, true
}

// SetPatternNames sets field value
func (o *CreateLogMappingRequestBodyFieldsUnstructuredFields) SetPatternNames(v []string) {
	o.PatternNames = v
}

func (o CreateLogMappingRequestBodyFieldsUnstructuredFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLogMappingRequestBodyFieldsUnstructuredFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["patternNames"] = o.PatternNames
	return toSerialize, nil
}

func (o *CreateLogMappingRequestBodyFieldsUnstructuredFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"patternNames",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLogMappingRequestBodyFieldsUnstructuredFields := _CreateLogMappingRequestBodyFieldsUnstructuredFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateLogMappingRequestBodyFieldsUnstructuredFields)

	if err != nil {
		return err
	}

	*o = CreateLogMappingRequestBodyFieldsUnstructuredFields(varCreateLogMappingRequestBodyFieldsUnstructuredFields)

	return err
}

type NullableCreateLogMappingRequestBodyFieldsUnstructuredFields struct {
	value *CreateLogMappingRequestBodyFieldsUnstructuredFields
	isSet bool
}

func (v NullableCreateLogMappingRequestBodyFieldsUnstructuredFields) Get() *CreateLogMappingRequestBodyFieldsUnstructuredFields {
	return v.value
}

func (v *NullableCreateLogMappingRequestBodyFieldsUnstructuredFields) Set(val *CreateLogMappingRequestBodyFieldsUnstructuredFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLogMappingRequestBodyFieldsUnstructuredFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLogMappingRequestBodyFieldsUnstructuredFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLogMappingRequestBodyFieldsUnstructuredFields(val *CreateLogMappingRequestBodyFieldsUnstructuredFields) *NullableCreateLogMappingRequestBodyFieldsUnstructuredFields {
	return &NullableCreateLogMappingRequestBodyFieldsUnstructuredFields{value: val, isSet: true}
}

func (v NullableCreateLogMappingRequestBodyFieldsUnstructuredFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLogMappingRequestBodyFieldsUnstructuredFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


