/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveSignalsFromInsightResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveSignalsFromInsightResponse{}

// RemoveSignalsFromInsightResponse struct for RemoveSignalsFromInsightResponse
type RemoveSignalsFromInsightResponse struct {
	Data Insight `json:"data"`
}

type _RemoveSignalsFromInsightResponse RemoveSignalsFromInsightResponse

// NewRemoveSignalsFromInsightResponse instantiates a new RemoveSignalsFromInsightResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveSignalsFromInsightResponse(data Insight) *RemoveSignalsFromInsightResponse {
	this := RemoveSignalsFromInsightResponse{}
	this.Data = data
	return &this
}

// NewRemoveSignalsFromInsightResponseWithDefaults instantiates a new RemoveSignalsFromInsightResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveSignalsFromInsightResponseWithDefaults() *RemoveSignalsFromInsightResponse {
	this := RemoveSignalsFromInsightResponse{}
	return &this
}

// GetData returns the Data field value
func (o *RemoveSignalsFromInsightResponse) GetData() Insight {
	if o == nil {
		var ret Insight
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RemoveSignalsFromInsightResponse) GetDataOk() (*Insight, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RemoveSignalsFromInsightResponse) SetData(v Insight) {
	o.Data = v
}

func (o RemoveSignalsFromInsightResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveSignalsFromInsightResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RemoveSignalsFromInsightResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveSignalsFromInsightResponse := _RemoveSignalsFromInsightResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveSignalsFromInsightResponse)

	if err != nil {
		return err
	}

	*o = RemoveSignalsFromInsightResponse(varRemoveSignalsFromInsightResponse)

	return err
}

type NullableRemoveSignalsFromInsightResponse struct {
	value *RemoveSignalsFromInsightResponse
	isSet bool
}

func (v NullableRemoveSignalsFromInsightResponse) Get() *RemoveSignalsFromInsightResponse {
	return v.value
}

func (v *NullableRemoveSignalsFromInsightResponse) Set(val *RemoveSignalsFromInsightResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveSignalsFromInsightResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveSignalsFromInsightResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveSignalsFromInsightResponse(val *RemoveSignalsFromInsightResponse) *NullableRemoveSignalsFromInsightResponse {
	return &NullableRemoveSignalsFromInsightResponse{value: val, isSet: true}
}

func (v NullableRemoveSignalsFromInsightResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveSignalsFromInsightResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


