/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveSignalsFromInsightRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveSignalsFromInsightRequestBody{}

// RemoveSignalsFromInsightRequestBody struct for RemoveSignalsFromInsightRequestBody
type RemoveSignalsFromInsightRequestBody struct {
	SignalIds []string `json:"signalIds"`
}

type _RemoveSignalsFromInsightRequestBody RemoveSignalsFromInsightRequestBody

// NewRemoveSignalsFromInsightRequestBody instantiates a new RemoveSignalsFromInsightRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveSignalsFromInsightRequestBody(signalIds []string) *RemoveSignalsFromInsightRequestBody {
	this := RemoveSignalsFromInsightRequestBody{}
	this.SignalIds = signalIds
	return &this
}

// NewRemoveSignalsFromInsightRequestBodyWithDefaults instantiates a new RemoveSignalsFromInsightRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveSignalsFromInsightRequestBodyWithDefaults() *RemoveSignalsFromInsightRequestBody {
	this := RemoveSignalsFromInsightRequestBody{}
	return &this
}

// GetSignalIds returns the SignalIds field value
func (o *RemoveSignalsFromInsightRequestBody) GetSignalIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SignalIds
}

// GetSignalIdsOk returns a tuple with the SignalIds field value
// and a boolean to check if the value has been set.
func (o *RemoveSignalsFromInsightRequestBody) GetSignalIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignalIds, true
}

// SetSignalIds sets field value
func (o *RemoveSignalsFromInsightRequestBody) SetSignalIds(v []string) {
	o.SignalIds = v
}

func (o RemoveSignalsFromInsightRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveSignalsFromInsightRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signalIds"] = o.SignalIds
	return toSerialize, nil
}

func (o *RemoveSignalsFromInsightRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signalIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveSignalsFromInsightRequestBody := _RemoveSignalsFromInsightRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveSignalsFromInsightRequestBody)

	if err != nil {
		return err
	}

	*o = RemoveSignalsFromInsightRequestBody(varRemoveSignalsFromInsightRequestBody)

	return err
}

type NullableRemoveSignalsFromInsightRequestBody struct {
	value *RemoveSignalsFromInsightRequestBody
	isSet bool
}

func (v NullableRemoveSignalsFromInsightRequestBody) Get() *RemoveSignalsFromInsightRequestBody {
	return v.value
}

func (v *NullableRemoveSignalsFromInsightRequestBody) Set(val *RemoveSignalsFromInsightRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveSignalsFromInsightRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveSignalsFromInsightRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveSignalsFromInsightRequestBody(val *RemoveSignalsFromInsightRequestBody) *NullableRemoveSignalsFromInsightRequestBody {
	return &NullableRemoveSignalsFromInsightRequestBody{value: val, isSet: true}
}

func (v NullableRemoveSignalsFromInsightRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveSignalsFromInsightRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


