/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddTagToInsightResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddTagToInsightResponse{}

// AddTagToInsightResponse struct for AddTagToInsightResponse
type AddTagToInsightResponse struct {
	Data Insight `json:"data"`
}

type _AddTagToInsightResponse AddTagToInsightResponse

// NewAddTagToInsightResponse instantiates a new AddTagToInsightResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTagToInsightResponse(data Insight) *AddTagToInsightResponse {
	this := AddTagToInsightResponse{}
	this.Data = data
	return &this
}

// NewAddTagToInsightResponseWithDefaults instantiates a new AddTagToInsightResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTagToInsightResponseWithDefaults() *AddTagToInsightResponse {
	this := AddTagToInsightResponse{}
	return &this
}

// GetData returns the Data field value
func (o *AddTagToInsightResponse) GetData() Insight {
	if o == nil {
		var ret Insight
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AddTagToInsightResponse) GetDataOk() (*Insight, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AddTagToInsightResponse) SetData(v Insight) {
	o.Data = v
}

func (o AddTagToInsightResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddTagToInsightResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AddTagToInsightResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddTagToInsightResponse := _AddTagToInsightResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddTagToInsightResponse)

	if err != nil {
		return err
	}

	*o = AddTagToInsightResponse(varAddTagToInsightResponse)

	return err
}

type NullableAddTagToInsightResponse struct {
	value *AddTagToInsightResponse
	isSet bool
}

func (v NullableAddTagToInsightResponse) Get() *AddTagToInsightResponse {
	return v.value
}

func (v *NullableAddTagToInsightResponse) Set(val *AddTagToInsightResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTagToInsightResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTagToInsightResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTagToInsightResponse(val *AddTagToInsightResponse) *NullableAddTagToInsightResponse {
	return &NullableAddTagToInsightResponse{value: val, isSet: true}
}

func (v NullableAddTagToInsightResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTagToInsightResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


