/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkUpdateEntityWhitelistResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkUpdateEntityWhitelistResponse{}

// BulkUpdateEntityWhitelistResponse struct for BulkUpdateEntityWhitelistResponse
type BulkUpdateEntityWhitelistResponse struct {
	Data []BulkUpdateEntityWhitelistResponseDataInner `json:"data"`
}

type _BulkUpdateEntityWhitelistResponse BulkUpdateEntityWhitelistResponse

// NewBulkUpdateEntityWhitelistResponse instantiates a new BulkUpdateEntityWhitelistResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkUpdateEntityWhitelistResponse(data []BulkUpdateEntityWhitelistResponseDataInner) *BulkUpdateEntityWhitelistResponse {
	this := BulkUpdateEntityWhitelistResponse{}
	this.Data = data
	return &this
}

// NewBulkUpdateEntityWhitelistResponseWithDefaults instantiates a new BulkUpdateEntityWhitelistResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkUpdateEntityWhitelistResponseWithDefaults() *BulkUpdateEntityWhitelistResponse {
	this := BulkUpdateEntityWhitelistResponse{}
	return &this
}

// GetData returns the Data field value
func (o *BulkUpdateEntityWhitelistResponse) GetData() []BulkUpdateEntityWhitelistResponseDataInner {
	if o == nil {
		var ret []BulkUpdateEntityWhitelistResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BulkUpdateEntityWhitelistResponse) GetDataOk() ([]BulkUpdateEntityWhitelistResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BulkUpdateEntityWhitelistResponse) SetData(v []BulkUpdateEntityWhitelistResponseDataInner) {
	o.Data = v
}

func (o BulkUpdateEntityWhitelistResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkUpdateEntityWhitelistResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BulkUpdateEntityWhitelistResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkUpdateEntityWhitelistResponse := _BulkUpdateEntityWhitelistResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkUpdateEntityWhitelistResponse)

	if err != nil {
		return err
	}

	*o = BulkUpdateEntityWhitelistResponse(varBulkUpdateEntityWhitelistResponse)

	return err
}

type NullableBulkUpdateEntityWhitelistResponse struct {
	value *BulkUpdateEntityWhitelistResponse
	isSet bool
}

func (v NullableBulkUpdateEntityWhitelistResponse) Get() *BulkUpdateEntityWhitelistResponse {
	return v.value
}

func (v *NullableBulkUpdateEntityWhitelistResponse) Set(val *BulkUpdateEntityWhitelistResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkUpdateEntityWhitelistResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkUpdateEntityWhitelistResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkUpdateEntityWhitelistResponse(val *BulkUpdateEntityWhitelistResponse) *NullableBulkUpdateEntityWhitelistResponse {
	return &NullableBulkUpdateEntityWhitelistResponse{value: val, isSet: true}
}

func (v NullableBulkUpdateEntityWhitelistResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkUpdateEntityWhitelistResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


