/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEntityValueResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEntityValueResponse{}

// CreateEntityValueResponse struct for CreateEntityValueResponse
type CreateEntityValueResponse struct {
	Data EntityValue `json:"data"`
}

type _CreateEntityValueResponse CreateEntityValueResponse

// NewCreateEntityValueResponse instantiates a new CreateEntityValueResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEntityValueResponse(data EntityValue) *CreateEntityValueResponse {
	this := CreateEntityValueResponse{}
	this.Data = data
	return &this
}

// NewCreateEntityValueResponseWithDefaults instantiates a new CreateEntityValueResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEntityValueResponseWithDefaults() *CreateEntityValueResponse {
	this := CreateEntityValueResponse{}
	return &this
}

// GetData returns the Data field value
func (o *CreateEntityValueResponse) GetData() EntityValue {
	if o == nil {
		var ret EntityValue
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateEntityValueResponse) GetDataOk() (*EntityValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateEntityValueResponse) SetData(v EntityValue) {
	o.Data = v
}

func (o CreateEntityValueResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEntityValueResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateEntityValueResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEntityValueResponse := _CreateEntityValueResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEntityValueResponse)

	if err != nil {
		return err
	}

	*o = CreateEntityValueResponse(varCreateEntityValueResponse)

	return err
}

type NullableCreateEntityValueResponse struct {
	value *CreateEntityValueResponse
	isSet bool
}

func (v NullableCreateEntityValueResponse) Get() *CreateEntityValueResponse {
	return v.value
}

func (v *NullableCreateEntityValueResponse) Set(val *CreateEntityValueResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEntityValueResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEntityValueResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEntityValueResponse(val *CreateEntityValueResponse) *NullableCreateEntityValueResponse {
	return &NullableCreateEntityValueResponse{value: val, isSet: true}
}

func (v NullableCreateEntityValueResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEntityValueResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


