/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetInsightsResponseDataObjectsInnerStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInsightsResponseDataObjectsInnerStatus{}

// GetInsightsResponseDataObjectsInnerStatus The current status of this Insight
type GetInsightsResponseDataObjectsInnerStatus struct {
	Name string `json:"name"`
	DisplayName string `json:"displayName"`
}

type _GetInsightsResponseDataObjectsInnerStatus GetInsightsResponseDataObjectsInnerStatus

// NewGetInsightsResponseDataObjectsInnerStatus instantiates a new GetInsightsResponseDataObjectsInnerStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInsightsResponseDataObjectsInnerStatus(name string, displayName string) *GetInsightsResponseDataObjectsInnerStatus {
	this := GetInsightsResponseDataObjectsInnerStatus{}
	this.Name = name
	this.DisplayName = displayName
	return &this
}

// NewGetInsightsResponseDataObjectsInnerStatusWithDefaults instantiates a new GetInsightsResponseDataObjectsInnerStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInsightsResponseDataObjectsInnerStatusWithDefaults() *GetInsightsResponseDataObjectsInnerStatus {
	this := GetInsightsResponseDataObjectsInnerStatus{}
	return &this
}

// GetName returns the Name field value
func (o *GetInsightsResponseDataObjectsInnerStatus) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetInsightsResponseDataObjectsInnerStatus) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetInsightsResponseDataObjectsInnerStatus) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *GetInsightsResponseDataObjectsInnerStatus) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *GetInsightsResponseDataObjectsInnerStatus) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *GetInsightsResponseDataObjectsInnerStatus) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o GetInsightsResponseDataObjectsInnerStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInsightsResponseDataObjectsInnerStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	return toSerialize, nil
}

func (o *GetInsightsResponseDataObjectsInnerStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"displayName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetInsightsResponseDataObjectsInnerStatus := _GetInsightsResponseDataObjectsInnerStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetInsightsResponseDataObjectsInnerStatus)

	if err != nil {
		return err
	}

	*o = GetInsightsResponseDataObjectsInnerStatus(varGetInsightsResponseDataObjectsInnerStatus)

	return err
}

type NullableGetInsightsResponseDataObjectsInnerStatus struct {
	value *GetInsightsResponseDataObjectsInnerStatus
	isSet bool
}

func (v NullableGetInsightsResponseDataObjectsInnerStatus) Get() *GetInsightsResponseDataObjectsInnerStatus {
	return v.value
}

func (v *NullableGetInsightsResponseDataObjectsInnerStatus) Set(val *GetInsightsResponseDataObjectsInnerStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInsightsResponseDataObjectsInnerStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInsightsResponseDataObjectsInnerStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInsightsResponseDataObjectsInnerStatus(val *GetInsightsResponseDataObjectsInnerStatus) *NullableGetInsightsResponseDataObjectsInnerStatus {
	return &NullableGetInsightsResponseDataObjectsInnerStatus{value: val, isSet: true}
}

func (v NullableGetInsightsResponseDataObjectsInnerStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInsightsResponseDataObjectsInnerStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


