/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateInsightAssigneeRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateInsightAssigneeRequestBody{}

// UpdateInsightAssigneeRequestBody struct for UpdateInsightAssigneeRequestBody
type UpdateInsightAssigneeRequestBody struct {
	Assignee *UpdateInsightAssigneeRequestBodyAssignee `json:"assignee,omitempty"`
}

// NewUpdateInsightAssigneeRequestBody instantiates a new UpdateInsightAssigneeRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateInsightAssigneeRequestBody() *UpdateInsightAssigneeRequestBody {
	this := UpdateInsightAssigneeRequestBody{}
	return &this
}

// NewUpdateInsightAssigneeRequestBodyWithDefaults instantiates a new UpdateInsightAssigneeRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateInsightAssigneeRequestBodyWithDefaults() *UpdateInsightAssigneeRequestBody {
	this := UpdateInsightAssigneeRequestBody{}
	return &this
}

// GetAssignee returns the Assignee field value if set, zero value otherwise.
func (o *UpdateInsightAssigneeRequestBody) GetAssignee() UpdateInsightAssigneeRequestBodyAssignee {
	if o == nil || IsNil(o.Assignee) {
		var ret UpdateInsightAssigneeRequestBodyAssignee
		return ret
	}
	return *o.Assignee
}

// GetAssigneeOk returns a tuple with the Assignee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateInsightAssigneeRequestBody) GetAssigneeOk() (*UpdateInsightAssigneeRequestBodyAssignee, bool) {
	if o == nil || IsNil(o.Assignee) {
		return nil, false
	}
	return o.Assignee, true
}

// HasAssignee returns a boolean if a field has been set.
func (o *UpdateInsightAssigneeRequestBody) HasAssignee() bool {
	if o != nil && !IsNil(o.Assignee) {
		return true
	}

	return false
}

// SetAssignee gets a reference to the given UpdateInsightAssigneeRequestBodyAssignee and assigns it to the Assignee field.
func (o *UpdateInsightAssigneeRequestBody) SetAssignee(v UpdateInsightAssigneeRequestBodyAssignee) {
	o.Assignee = &v
}

func (o UpdateInsightAssigneeRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateInsightAssigneeRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Assignee) {
		toSerialize["assignee"] = o.Assignee
	}
	return toSerialize, nil
}

type NullableUpdateInsightAssigneeRequestBody struct {
	value *UpdateInsightAssigneeRequestBody
	isSet bool
}

func (v NullableUpdateInsightAssigneeRequestBody) Get() *UpdateInsightAssigneeRequestBody {
	return v.value
}

func (v *NullableUpdateInsightAssigneeRequestBody) Set(val *UpdateInsightAssigneeRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInsightAssigneeRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInsightAssigneeRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInsightAssigneeRequestBody(val *UpdateInsightAssigneeRequestBody) *NullableUpdateInsightAssigneeRequestBody {
	return &NullableUpdateInsightAssigneeRequestBody{value: val, isSet: true}
}

func (v NullableUpdateInsightAssigneeRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInsightAssigneeRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


