/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetMatchListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMatchListResponse{}

// GetMatchListResponse struct for GetMatchListResponse
type GetMatchListResponse struct {
	Data MatchList `json:"data"`
}

type _GetMatchListResponse GetMatchListResponse

// NewGetMatchListResponse instantiates a new GetMatchListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMatchListResponse(data MatchList) *GetMatchListResponse {
	this := GetMatchListResponse{}
	this.Data = data
	return &this
}

// NewGetMatchListResponseWithDefaults instantiates a new GetMatchListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMatchListResponseWithDefaults() *GetMatchListResponse {
	this := GetMatchListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetMatchListResponse) GetData() MatchList {
	if o == nil {
		var ret MatchList
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetMatchListResponse) GetDataOk() (*MatchList, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetMatchListResponse) SetData(v MatchList) {
	o.Data = v
}

func (o GetMatchListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMatchListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetMatchListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetMatchListResponse := _GetMatchListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetMatchListResponse)

	if err != nil {
		return err
	}

	*o = GetMatchListResponse(varGetMatchListResponse)

	return err
}

type NullableGetMatchListResponse struct {
	value *GetMatchListResponse
	isSet bool
}

func (v NullableGetMatchListResponse) Get() *GetMatchListResponse {
	return v.value
}

func (v *NullableGetMatchListResponse) Set(val *GetMatchListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMatchListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMatchListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMatchListResponse(val *GetMatchListResponse) *NullableGetMatchListResponse {
	return &NullableGetMatchListResponse{value: val, isSet: true}
}

func (v NullableGetMatchListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMatchListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


