/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAggregationRuleRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAggregationRuleRequestBody{}

// CreateAggregationRuleRequestBody struct for CreateAggregationRuleRequestBody
type CreateAggregationRuleRequestBody struct {
	Fields CreateAggregationRuleRequestBodyFields `json:"fields"`
}

type _CreateAggregationRuleRequestBody CreateAggregationRuleRequestBody

// NewCreateAggregationRuleRequestBody instantiates a new CreateAggregationRuleRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAggregationRuleRequestBody(fields CreateAggregationRuleRequestBodyFields) *CreateAggregationRuleRequestBody {
	this := CreateAggregationRuleRequestBody{}
	this.Fields = fields
	return &this
}

// NewCreateAggregationRuleRequestBodyWithDefaults instantiates a new CreateAggregationRuleRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAggregationRuleRequestBodyWithDefaults() *CreateAggregationRuleRequestBody {
	this := CreateAggregationRuleRequestBody{}
	return &this
}

// GetFields returns the Fields field value
func (o *CreateAggregationRuleRequestBody) GetFields() CreateAggregationRuleRequestBodyFields {
	if o == nil {
		var ret CreateAggregationRuleRequestBodyFields
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *CreateAggregationRuleRequestBody) GetFieldsOk() (*CreateAggregationRuleRequestBodyFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fields, true
}

// SetFields sets field value
func (o *CreateAggregationRuleRequestBody) SetFields(v CreateAggregationRuleRequestBodyFields) {
	o.Fields = v
}

func (o CreateAggregationRuleRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAggregationRuleRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

func (o *CreateAggregationRuleRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAggregationRuleRequestBody := _CreateAggregationRuleRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAggregationRuleRequestBody)

	if err != nil {
		return err
	}

	*o = CreateAggregationRuleRequestBody(varCreateAggregationRuleRequestBody)

	return err
}

type NullableCreateAggregationRuleRequestBody struct {
	value *CreateAggregationRuleRequestBody
	isSet bool
}

func (v NullableCreateAggregationRuleRequestBody) Get() *CreateAggregationRuleRequestBody {
	return v.value
}

func (v *NullableCreateAggregationRuleRequestBody) Set(val *CreateAggregationRuleRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAggregationRuleRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAggregationRuleRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAggregationRuleRequestBody(val *CreateAggregationRuleRequestBody) *NullableCreateAggregationRuleRequestBody {
	return &NullableCreateAggregationRuleRequestBody{value: val, isSet: true}
}

func (v NullableCreateAggregationRuleRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAggregationRuleRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


