/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetMatchListsResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMatchListsResponseData{}

// GetMatchListsResponseData struct for GetMatchListsResponseData
type GetMatchListsResponseData struct {
	HasNextPage bool `json:"hasNextPage"`
	Total int32 `json:"total"`
	Objects []MatchList `json:"objects"`
}

type _GetMatchListsResponseData GetMatchListsResponseData

// NewGetMatchListsResponseData instantiates a new GetMatchListsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMatchListsResponseData(hasNextPage bool, total int32, objects []MatchList) *GetMatchListsResponseData {
	this := GetMatchListsResponseData{}
	this.HasNextPage = hasNextPage
	this.Total = total
	this.Objects = objects
	return &this
}

// NewGetMatchListsResponseDataWithDefaults instantiates a new GetMatchListsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMatchListsResponseDataWithDefaults() *GetMatchListsResponseData {
	this := GetMatchListsResponseData{}
	return &this
}

// GetHasNextPage returns the HasNextPage field value
func (o *GetMatchListsResponseData) GetHasNextPage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNextPage
}

// GetHasNextPageOk returns a tuple with the HasNextPage field value
// and a boolean to check if the value has been set.
func (o *GetMatchListsResponseData) GetHasNextPageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasNextPage, true
}

// SetHasNextPage sets field value
func (o *GetMatchListsResponseData) SetHasNextPage(v bool) {
	o.HasNextPage = v
}

// GetTotal returns the Total field value
func (o *GetMatchListsResponseData) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetMatchListsResponseData) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetMatchListsResponseData) SetTotal(v int32) {
	o.Total = v
}

// GetObjects returns the Objects field value
func (o *GetMatchListsResponseData) GetObjects() []MatchList {
	if o == nil {
		var ret []MatchList
		return ret
	}

	return o.Objects
}

// GetObjectsOk returns a tuple with the Objects field value
// and a boolean to check if the value has been set.
func (o *GetMatchListsResponseData) GetObjectsOk() ([]MatchList, bool) {
	if o == nil {
		return nil, false
	}
	return o.Objects, true
}

// SetObjects sets field value
func (o *GetMatchListsResponseData) SetObjects(v []MatchList) {
	o.Objects = v
}

func (o GetMatchListsResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMatchListsResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hasNextPage"] = o.HasNextPage
	toSerialize["total"] = o.Total
	toSerialize["objects"] = o.Objects
	return toSerialize, nil
}

func (o *GetMatchListsResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hasNextPage",
		"total",
		"objects",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetMatchListsResponseData := _GetMatchListsResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetMatchListsResponseData)

	if err != nil {
		return err
	}

	*o = GetMatchListsResponseData(varGetMatchListsResponseData)

	return err
}

type NullableGetMatchListsResponseData struct {
	value *GetMatchListsResponseData
	isSet bool
}

func (v NullableGetMatchListsResponseData) Get() *GetMatchListsResponseData {
	return v.value
}

func (v *NullableGetMatchListsResponseData) Set(val *GetMatchListsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMatchListsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMatchListsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMatchListsResponseData(val *GetMatchListsResponseData) *NullableGetMatchListsResponseData {
	return &NullableGetMatchListsResponseData{value: val, isSet: true}
}

func (v NullableGetMatchListsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMatchListsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


