/*
Sumo Logic CSE API

 https://help.sumologic.com/APIs 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologiccsiem

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetEntityNotesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEntityNotesResponse{}

// GetEntityNotesResponse struct for GetEntityNotesResponse
type GetEntityNotesResponse struct {
	Data []GetEntityNotesResponseDataInner `json:"data"`
}

type _GetEntityNotesResponse GetEntityNotesResponse

// NewGetEntityNotesResponse instantiates a new GetEntityNotesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEntityNotesResponse(data []GetEntityNotesResponseDataInner) *GetEntityNotesResponse {
	this := GetEntityNotesResponse{}
	this.Data = data
	return &this
}

// NewGetEntityNotesResponseWithDefaults instantiates a new GetEntityNotesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEntityNotesResponseWithDefaults() *GetEntityNotesResponse {
	this := GetEntityNotesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetEntityNotesResponse) GetData() []GetEntityNotesResponseDataInner {
	if o == nil {
		var ret []GetEntityNotesResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetEntityNotesResponse) GetDataOk() ([]GetEntityNotesResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetEntityNotesResponse) SetData(v []GetEntityNotesResponseDataInner) {
	o.Data = v
}

func (o GetEntityNotesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEntityNotesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetEntityNotesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEntityNotesResponse := _GetEntityNotesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetEntityNotesResponse)

	if err != nil {
		return err
	}

	*o = GetEntityNotesResponse(varGetEntityNotesResponse)

	return err
}

type NullableGetEntityNotesResponse struct {
	value *GetEntityNotesResponse
	isSet bool
}

func (v NullableGetEntityNotesResponse) Get() *GetEntityNotesResponse {
	return v.value
}

func (v *NullableGetEntityNotesResponse) Set(val *GetEntityNotesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEntityNotesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEntityNotesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEntityNotesResponse(val *GetEntityNotesResponse) *NullableGetEntityNotesResponse {
	return &NullableGetEntityNotesResponse{value: val, isSet: true}
}

func (v NullableGetEntityNotesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEntityNotesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


